# cf0:
#   uri: radio://0/80/2M/E7E7E7E700
# cf1:
#   uri: radio://0/80/2M/E7E7E7E701
# cf2:
#   uri: radio://0/80/2M/E7E7E7E702

# cf0:
#   uri: radio://0/80/2M/E7E7E7E700
# cf1:
#   uri: radio://0/80/2M/E7E7E7E701
cf0:
  uri: radio://0/80/2M/E7E7E7E703
# cf1:
#   uri: radio://0/80/2M/E7E7E7E710
# cf0:
#   uri: radio://0/80/2M/E7E7E7E711
# cf1:
#   uri: radio://0/80/2M/E7E7E7E712
